### ISSUE TITLE
Crash while listening to a subscribed channel

### ISSUE THREAD

**Issue by vlavianos** [xively/xively-mobile-sdk-ios#4]
We were subscribed to a channel of type Timeseries. After some time the app crashed with the following error:

`Assertion failed: (0), function -[MQTTDecoder stream:handleEvent:], file /Users/autobuilder/build.tc/halleberg-mac/work/6d6e37b167114a5f/src/MqttSDK/MQTTDecoder.m, line 74.`

The error above happened only once and we couldn't reproduce again.

However, please note that the path in the error is not from our environment. (As if there is a forgotten hardcoded path somewhere in the code)

**Comment by jandr50** [comment]
I'm seeing this same issue, though the file name seems to have changed: 

`Assertion failed: (0), function -[MQTTDecoder stream:handleEvent:], file /Users/gszajko/Development/work/xively-mobile-sdk-ios/XivelySDKiOS/src/common-iOS/common-iOS/Paho/MQTTDecoder.m, line 74.`

[This link](https://github.com/novastone-media/MQTT-Client-Framework/issues/21) implies there's an object that is getting deallocated without cleaning itself up..
